on:
  issues:
    types: 
      - opened

jobs:
  duplication_detect_job:
    runs-on: ubuntu-latest
    name: A job to detect duplication among issues

    env:
      rapid_key: ${{ secrets.RAPID_KEY }}
      repo_key: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Duplication scan action step
        uses: prosyslab/dude@v1.0.0
        id: dup_scan
        with:
          issue_num: ${{ github.event.issue.number }}
          issue_contents: ${{ github.event.issue.body }}
          repository_path_name: ${{ github.repository }}
          rapid_key: ${{ env.rapid_key }}
          repo_key: ${{ env.repo_key }}
